### ISSUE TITLE
Implement mkdir

### ISSUE THREAD

**Issue by as27** [as27/gomd#12]
The command should be:

`mkdir new_folder`
`mkdir new folder`

The new folder should be added at the left side.

**Comment by ananichev** [comment]
@as27  Please review my PR https://github.com/as27/gomd/pull/16

**Comment by as27** [comment]
I merged the PR, but messed up a little bit by resolving the conflicts. 

Just checked what your function does and we should change the behaviour. I think that is my fault, because a I didn't write enough information. Just change it and make another PR.

How it should work:

`mkdir new_folder` -> creates "`new_folder`"
`mkdir new folder` -> creates "`new folder`" (just one folder not `new/folder`)
`mkdir foo/bar` -> creates "`foo`" and inside "`foo`" another folder "`bar`"

I think you just have to change the split logic.

**Comment by ananichev** [comment]
No problem
will do this

**Comment by as27** [comment]
Looks good now. Thank you.
